version: '3.7'

networks:
  ftp-net:
    driver: bridge

services:
  ftp-server:
    container_name: ftp-server
    build:
      dockerfile: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - ftp-net
    environment:
      - FTP_USER=mounadi
      - FTP_PASS=test06
    restart: always
 
  client1:
    container_name: client1
    build:
      dockerfile: client
    depends_on:
      - ftp-server
    networks:
      - ftp-net
    stdin_open: true
    tty: true

  client2:
    container_name: client2
    build:
      dockerfile: client
    depends_on:
      - ftp-server
    networks:
      - ftp-net
    stdin_open: true
    tty: true
  
  attacker:
    container_name: attacker
    build:
      dockerfile: attacker
    privileged: true
    depends_on:
      - ftp-server
    networks:
      - ftp-net
    stdin_open: true
    tty: true
  
  chat-server:
    container_name: chat-server
    build:
      dockerfile: chat-server
    ports:
      - "9099:9099"
    networks:
      - ftp-net
    restart: always



